### ISSUE TITLE
Cleanup ConfigurationKey

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-interfaces#32]
The class ConfigurationKey have still SAML_SP and STS enums like SSO_IDP_AUTHENTICATION_REQUEST_HTTP_METHOD or SSO_STS_ENCKEY_LEN. With the introduction of OIDC this enums are not longer needed an can be removed. It should be tested carefully if any sideeffects will occure.

**Comment by kowalczyka** [comment]
Closing as it is included in https://github.com/servicecatalog/oscm/issues/386
